### ISSUE TITLE
Bug: WebGPU Initialization Fails in Microsoft Edge on ARM64 and AMD64 Devices

### ISSUE THREAD

**Issue by arudaev** [supabase-community/babelfish.ai#8]
# Bug Report

## Describe the bug

When using the Edge browser on both ARM64 and AMD64 devices with WebGPU enabled, the application fails to initialize WebGPU. Despite `edge://gpu` indicating that WebGPU is enabled, the following error is encountered in the console:

```
transcriptionWorker-BL8v9X_F.js:5
Uncaught (in promise) Error: no available backend found. ERR: [webgpu] Error: Failed to get GPU adapter. You may need to enable flag "--enable-unsafe-webgpu" if you are using Chrome.
    at hs (https://supabase-community.github.io/babelfish.ai/assets/transcriptionWorker-BL8v9X_F.js:5:1599)
    at async V_.create (https://supabase-community.github.io/babelfish.ai/assets/transcriptionWorker-BL8v9X_F.js:5:17973)
    at async Xf (https://supabase-community.github.io/babelfish.ai/assets/transcriptionWorker-BL8v9X_F.js:2353:12683)
    at async Qr (https://supabase-community.github.io/babelfish.ai/assets/transcriptionWorker-BL8v9X_F.js:2373:27599)
    at async Promise.all (index 0)
    at async Ym.from_pretrained (https://supabase-community.github.io/babelfish.ai/assets/transcriptionWorker-BL8v9X_F.js:2373:33819)
    at async Promise.all (index 2)
    at async F3 (https://supabase-community.github.io/babelfish.ai/assets/transcriptionWorker-BL8v9X_F.js:2375:1225)
```

## Expected behavior

The application should successfully initialize and utilize WebGPU without requiring additional flags or encountering backend errors. Users should be able to leverage GPU-accelerated features seamlessly in the Edge browser.

## Screenshots

![Webapp with console error message](https://github.com/user-attachments/assets/f550ef79-df98-4f87-aec8-26fd6233b0b8)

![Edge GPU report](https://github.com/user-attachments/assets/8634302c-0200-44e3-a329-21d95db9d920)

## System information

- **OS:** Windows 11 Home
- **Browser:** Microsoft Edge Version 131.0.2903.86 (Official build) (ARM64)
- **Device Architectures:** ARM64 and AMD64

## Additional context

- **WebGPU Status:** Enabled as confirmed by `edge://gpu`.
- **Attempted Solutions:** The error message suggests enabling the `--enable-unsafe-webgpu` flag for Chrome, but it is unclear if this applies to Edge.
- **Reproducibility:** The issue occurs consistently on both ARM64 and AMD64 devices using the specified Edge browser version.
- **Potential Impact:** Users are unable to utilize GPU-accelerated functionalities provided by the application, which may degrade performance or disable certain features.

Please let me know if additional information is required to resolve this issue.

**Comment by leeprobert** [comment]
+1 - any luck with this? Did the flag work?
